{{- include "helm-library.cron-job" (list . "live-scores-publisher.cron-job") -}}
{{- define "live-scores-publisher.cron-job" -}}
metadata:
  name: {{ .Values.name }}
spec:
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  jobTemplate: 
    spec:
      template:
        spec:
          containers:
          - {{ include "helm-library.container" (list . "live-scores-publisher.container") | nindent 12 }}
{{- end -}}
