{{- include "helm-library.secret" (list . "live-scores-publisher.secret") -}}
{{- define "live-scores-publisher.secret" -}}
stringData:
  REDIS_PASSWORD: {{ .Values.container.redisPassword | quote }}
  MESSAGE_USERNAME: {{ quote .Values.container.messageUsername }}
  MESSAGE_PASSWORD: {{ quote .Values.container.messagePassword }}
{{- end -}}
