module.exports = {
  PREMIER_LEAGUE: 'PREMIER LEAGUE',
  CHAMPIONSHIP: 'CHAMPIONSHIP',
  LEAGUE_ONE: 'LEAGUE ONE',
  LEAGUE_TWO: 'LEAGUE TWO',
  FA_CUP: 'THE FA CUP',
  EFL_CUP: 'EFL CUP',
  WOMENS_WORLD_CUP: 'WOMEN\'S WORLD CUP'
}
