environment: production
name: live-scores-publisher
image: live-scores-publisher

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 500Mi
  limitCpu: 500m
  redisHost:
  redisPassword:
  messageHost:
  messageUsername:
  messagePassword:
  messageExchange: live-scores

cronJob: 
  schedule: "0/5 15-19 * * 6" # between 5 and 7 pm every Saturday
  concurrencyPolicy: Forbid
  restartPolicy: Never
  successfulJobsHistoryLimit: 1

secret:
  type: Opaque
