environment: development
name: live-scores-publisher
image: live-scores-publisher

container:
  imagePullPolicy: Always
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  redisHost:
  redisPassword:

deployment:
  restartPolicy: Always
  replicas: 1
  minReadySeconds: 5
