environment: production
name: live-scores-publisher
image: live-scores-publisher

container:
  requestMemory: 120Mi
  requestCpu: 120m
  limitMemory: 120Mi
  limitCpu: 120m
  redisHost:
  redisPassword:
  messageHost:
  messageUsername:
  messagePassword:
  messageExchange: live-scores
  apiHost: test-api
  apiKey: test-api-key

deployment: {}

secret:
  type: Opaque
